server:
  port: 8040



spring:
  data:
    mongodb:
      username: admin
      password: password
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: orderGroup,paymentGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'com.viggad.notification.kafka.*'
        spring.json.type.mapping: >
          orderConfirmation:com.viggad.notification.kafka.order.OrderConfirmation,
          paymentConfirmation:com.viggad.notification.kafka.payment.PaymentConfirmation

  mail:
    host: localhost
    port: 1025
    username: admin
    password: password
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
